//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRACHEL.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KRACHEL.WPF.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        public static string EelementAdd {
            get {
                return ResourceManager.GetString("EelementAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string ElementClose {
            get {
                return ResourceManager.GetString("ElementClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit.
        /// </summary>
        public static string ElementEdit {
            get {
                return ResourceManager.GetString("ElementEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzovat.
        /// </summary>
        public static string ElementFileAnalyze {
            get {
                return ResourceManager.GetString("ElementFileAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracovat.
        /// </summary>
        public static string ElementProcess {
            get {
                return ResourceManager.GetString("ElementProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        public static string ElementRemove {
            get {
                return ResourceManager.GetString("ElementRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit vše.
        /// </summary>
        public static string ElementRemoveAll {
            get {
                return ResourceManager.GetString("ElementRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string ElementSave {
            get {
                return ResourceManager.GetString("ElementSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procházet.
        /// </summary>
        public static string ElementSelectFile {
            get {
                return ResourceManager.GetString("ElementSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadit dle času.
        /// </summary>
        public static string ElementSortByTime {
            get {
                return ResourceManager.GetString("ElementSortByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracování se nezdařilo..
        /// </summary>
        public static string ErrorProcessingFailed {
            get {
                return ResourceManager.GetString("ErrorProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá zpracování, čekejte..
        /// </summary>
        public static string InformationRequestIsProcessed {
            get {
                return ResourceManager.GetString("InformationRequestIsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V čase.
        /// </summary>
        public static string LabelAtTime {
            get {
                return ResourceManager.GetString("LabelAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio stopa.
        /// </summary>
        public static string LabelAudioFile {
            get {
                return ResourceManager.GetString("LabelAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta k souboru.
        /// </summary>
        public static string LabelFilePath {
            get {
                return ResourceManager.GetString("LabelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodina.
        /// </summary>
        public static string LabelHour {
            get {
                return ResourceManager.GetString("LabelHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milisekunda.
        /// </summary>
        public static string LabelMilisecond {
            get {
                return ResourceManager.GetString("LabelMilisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuta.
        /// </summary>
        public static string LabelMinute {
            get {
                return ResourceManager.GetString("LabelMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umístění položky v čase.
        /// </summary>
        public static string LabelPartAtTime {
            get {
                return ResourceManager.GetString("LabelPartAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definice položky.
        /// </summary>
        public static string LabelPartDefinition {
            get {
                return ResourceManager.GetString("LabelPartDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam položek.
        /// </summary>
        public static string LabelPartList {
            get {
                return ResourceManager.GetString("LabelPartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit jako.
        /// </summary>
        public static string LabelSaveAs {
            get {
                return ResourceManager.GetString("LabelSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunda.
        /// </summary>
        public static string LabelSecond {
            get {
                return ResourceManager.GetString("LabelSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadný text.
        /// </summary>
        public static string LabelText {
            get {
                return ResourceManager.GetString("LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video soubor.
        /// </summary>
        public static string LabelVideoFile {
            get {
                return ResourceManager.GetString("LabelVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položky videa.
        /// </summary>
        public static string LabelVideoParts {
            get {
                return ResourceManager.GetString("LabelVideoParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ položky.
        /// </summary>
        public static string LabelVideoPartType {
            get {
                return ResourceManager.GetString("LabelVideoPartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio extraktor.
        /// </summary>
        public static string NameAudioExtractor {
            get {
                return ResourceManager.GetString("NameAudioExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        public static string NameInformation {
            get {
                return ResourceManager.GetString("NameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video editor.
        /// </summary>
        public static string NameVideoEditor {
            get {
                return ResourceManager.GetString("NameVideoEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka videa.
        /// </summary>
        public static string NameVideoPart {
            get {
                return ResourceManager.GetString("NameVideoPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varování.
        /// </summary>
        public static string NameWarning {
            get {
                return ResourceManager.GetString("NameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny podporované formáty.
        /// </summary>
        public static string PartAllSupportedFormats {
            get {
                return ResourceManager.GetString("PartAllSupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V čase.
        /// </summary>
        public static string PartAtTime {
            get {
                return ResourceManager.GetString("PartAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor.
        /// </summary>
        public static string PartFile {
            get {
                return ResourceManager.GetString("PartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte.
        /// </summary>
        public static string SelectItemDefault {
            get {
                return ResourceManager.GetString("SelectItemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prázdná obrazovka.
        /// </summary>
        public static string SelectItemVideoPartTypeBlankScreen {
            get {
                return ResourceManager.GetString("SelectItemVideoPartTypeBlankScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prázdná obrazovka se zadaným textem.
        /// </summary>
        public static string SelectItemVideoPartTypeBlankScreenText {
            get {
                return ResourceManager.GetString("SelectItemVideoPartTypeBlankScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafika ve formě obrázku.
        /// </summary>
        public static string SelectItemVideoPartTypeGraphic {
            get {
                return ResourceManager.GetString("SelectItemVideoPartTypeGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracování bylo úspěšně dokončeno..
        /// </summary>
        public static string SuccessProcessingOK {
            get {
                return ResourceManager.GetString("SuccessProcessingOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V čase 0:0:0:0 není umístěna žádná položka videa..
        /// </summary>
        public static string VideoEditorFirstPartMissing {
            get {
                return ResourceManager.GetString("VideoEditorFirstPartMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta k souboru není platná..
        /// </summary>
        public static string WarningFilePathIsNotValid {
            get {
                return ResourceManager.GetString("WarningFilePathIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyla vybrána žádná položka..
        /// </summary>
        public static string WarningSelectionIsEmpty {
            get {
                return ResourceManager.GetString("WarningSelectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není platné číslo..
        /// </summary>
        public static string WarningValueIsNotNumber {
            get {
                return ResourceManager.GetString("WarningValueIsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není platná hodnota..
        /// </summary>
        public static string WarningValueIsNotValid {
            get {
                return ResourceManager.GetString("WarningValueIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota je mimo povolený číselný rozsah..
        /// </summary>
        public static string WarningValueNumberOutOfRange {
            get {
                return ResourceManager.GetString("WarningValueNumberOutOfRange", resourceCulture);
            }
        }
    }
}
